---
- hosts: all
  become: yes
  tasks:
  - name: i want to install webserver on ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    

  - name: start the service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
    
  - name: i want to copy index file into all nodes
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
    when: ansible_os_family == "Debian"
    
  - name: restart the service
    service:
      name: apache2
      state: restarted
    when: ansible_os_family == "Debian"
